name: Lint

on:
  pull_request:
    branches:
      - main
      - develop
    paths:
      - src/laravel/**

jobs:
  lint:
    uses: ./.github/workflows/reusable-lint.yml

  add:
    name: lint additional
    runs-on: ubuntu-20.04
    needs: lint

    steps:
      - name: run
        run: |
          echo "lint additional run"

