name: Production Deploy to Amazon ECS

on:
  pull_request:
    branches:
      - main
    types:
      - closed
#    paths:
#      - src/laravel/**

env:
  aws_role_arn: AWS_ROLE_ARN
  ecs_cluster: ECS_CLUSTER
  ecs_service: ECS_SERVICE
  ecr_registry: ECR_REGISTRY # ${{ vars.AWS_ACCOUNT_ID }}.dkr.ecr.ap-northeast-1.amazonaws.com
  ecr_repository: ECR_REPOSITORY
  task_family: TASK_FAMILY
  ecs_service_subnets: ECS_SERVICE_SECURITY_GROUP # ${{ vars.ECS_STAGING_SERVICE_SUBNETS }}
  ecs_service_security_group: ECS_SERVICE_SECURITY_GROUP #${{ vars.ECS_SERVICE_SECURITY_GROUP }}

jobs:
#  lint:
#    name: lint
#    uses: ./.github/workflows/reusable-lint.yml
#    if: github.event.pull_request.merged == true

  build:
    name: Build And ECR Push
    uses: ./.github/workflows/reusable-build.yml
    with:
      environment: ${{ inputs.environment }}
      aws_role_arn: ${{ matrix.aws_role_arn }}
      ecr_registry: ecr_registry
      ecs_cluster: ecs_cluster
      supervisord_conf: supervisord_conf
      docker_file_path: docker_file_path
      task_definition: task_definition
      ecr_repository: ecr_repository
      ecs_service: ecs_service
    strategy:
      matrix:
        include:
          - env: production
            aws_role_arn: aws_role_arn_production
            environment: main
          - env: trial
            aws_role_arn: aws_role_arn_trial
            environment: main
#    needs:
#      - lint
    secrets: inherit

  migration:
    needs:
      - build
#      - lint
    uses: ./.github/workflows/reusable-migrate.yml
    with:
      aws_role_arn: ${{ env.aws_role_arn }}
      aws_region: ${{ env.aws_region }}
      ecs_cluster: ${{ env.ecs_cluster }}
      task_family: ${{ env.task_family }}
      ecs_service_subnets: ${{ env.ecs_service_subnets }}
      ecs_service_security_group: ${{ env.ecs_service_security_group }}
    strategy:
      matrix:
        include:
          - env: production
            aws_role_arn: ${{ secrets.AWS_ROLE_ARN }}
            aws_region: ${{ vars.AWS_REGION }}
            ecs_cluster: ecs_cluster_production
            task_family: task_family_production
            ecs_service_subnets: ecs_service_subnets_production
            ecs_service_security_group: ecs_service_security_group_production
            environment: production
          - env: trial
            aws_role_arn: ${{ secrets.AWS_ROLE_ARN }}
            aws_region: ${{ vars.AWS_REGION }}
            ecs_cluster: ecs_cluster_trial
            task_family: task_family_trial
            ecs_service_subnets: ecs_service_subnets_trial
            ecs_service_security_group: ecs_service_security_group_trial
            environment: trial
    secrets: inherit
    permissions:
      id-token: write
      contents: read
      pull-requests: write
