name: Staging Deploy to Amazon ECS

on:
  pull_request:
    branches:
      - develop
    types:
      - closed
    paths:
      - src/laravel/**
  workflow_dispatch:

env:
  AWS_ROLE_ARN: AWS_ROLE_ARN
  ECS_CLUSTER: ECS_CLUSTER
  ECS_SERVICE: ECS_SERVICE
  ECR_REGISTRY: ECR_REGISTRY # ${{ vars.AWS_ACCOUNT_ID }}.dkr.ecr.ap-northeast-1.amazonaws.com
  ECR_REPOSITORY: ECR_REPOSITORY
  TASK_FAMILY: TASK_FAMILY
  ECS_SERVICE_SUBNETS: ECS_SERVICE_SECURITY_GROUP # ${{ vars.ECS_STAGING_SERVICE_SUBNETS }}
  ECS_SERVICE_SECURITY_GROUP: ECS_SERVICE_SECURITY_GROUP #${{ vars.ECS_SERVICE_SECURITY_GROUP }}

jobs:
  lint:
    uses: ./.github/workflows/reusable-lint.yml

  build:
    name: Build And ECR Push
    runs-on: ubuntu-20.04
    if: github.event.pull_request.merged == true
    needs:
      - lint

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: develop

      - name: show env
        run: |
          ${{ env.AWS_ROLE_ARN }}
          ${{ env.ECR_REGISTRY }}
          ${{ env.ECR_REPOSITORY }}

  migration:
    uses: ./.github/workflows/reusable-migrate.yml
    with:
      aws-role-arn: aws-role-arn-from-staging-build
      aws-region: aws-region-from-staging-build
      ecs-cluster: ecs-cluster-from-staging-build
      task-family: task-family-from-staging-build
      ecs-service-subnets: ecs-service-subnets-from-staging-build
      ecs-service-security-group: ecs-service-security-group-from-staging-build
