name: Staging Deploy to Amazon ECS

on:
  pull_request:
    branches:
      - develop
    types:
      - closed
#    paths:
#      - src/laravel/**
  workflow_dispatch:

env:
  aws_role_arn: AWS_ROLE_ARN
  ecs_cluster: ECS_CLUSTER
  ecs_service: ECS_SERVICE
  ecr_registry: ECR_REGISTRY # ${{ vars.AWS_ACCOUNT_ID }}.dkr.ecr.ap-northeast-1.amazonaws.com
  ecr_repository: ECR_REPOSITORY
  task_family: TASK_FAMILY
  ecs_service_subnets: ECS_SERVICE_SECURITY_GROUP # ${{ vars.ECS_STAGING_SERVICE_SUBNETS }}
  ecs_service_security_group: ECS_SERVICE_SECURITY_GROUP #${{ vars.ECS_SERVICE_SECURITY_GROUP }}

jobs:
#  lint:
#    name: lint
#    uses: ./.github/workflows/reusable-lint.yml
#    if: github.event.pull_request.merged == true

  build:
    name: Build And ECR Push
    uses: ./.github/workflows/reusable-build.yml
    with:
      environment: ${{ matrix.environment }}
      aws_role_arn: ${{ matrix.aws_role_arn }}
      ecr_registry: ecr_registry
      ecs_cluster: ecs_cluster
      supervisord_conf: supervisord_conf
      docker_file_path: docker_file_path
      task_definition: task_definition
      ecr_repository: ecr_repository
      ecs_service: ecs_service
    strategy:
      matrix:
        include:
          - env: develop
            aws_role_arn: ${{ secrets.AWS_ROLE_ARN }}
            environment: staging
#    needs:
#      - lint
    secrets: inherit

  migration:
    needs:
      - build
#      - lint
    uses: ./.github/workflows/reusable-migrate.yml
    with:
      environment: staging
      aws_role_arn: aws_role_arn
      aws_region: ${{ vars.AWS_REGION }}
      ecs_cluster: ecs_cluster_trial
      task_family: task_family_trial
      ecs_service_subnets: ecs_service_subnets_trial
      ecs_service_security_group: ecs_service_security_group_trial
    secrets: inherit
    permissions:
      id-token: write
      contents: read
      pull-requests: write
